###Question 1:
A = [[2 -1 3], [0 4 1]]

B = [[ 1 2], [-2 0], [ 5 -3]]

AB = [[ 2•1 + (-1•-2) + 3•5 2•2 + (-1•0) + 3•(-3)], [0•1 + 4•(-2) + 1•5 0•2 + 4•0 + 1•(-3)]]

AB = [[19 -5], [-3 -3]]

###a. A has 2 rows and 3 columns i.e it is a 2by3 matrix, while B has 3 rows and 2 columns i.e it is a 3by2 matrix.
###b. The number of rows in A = number of rows in B, so  the matrix A can be multiplied by matrix B. both AB and BA multiplication are possible

In [ ]:
#!c.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
 

In [3]:
A = [[2, -1, 3], [0, 4, 1]]
B = [[1, 2], [-2, 0], [5, -3]]
AB = np.dot(A, B)
BA = np.dot(B, A)
print("Matrix A:")
print(np.array(A))
print("\nMatrix B:")
print(np.array(B))
print("\nMatrix AB (A multiplied by B):")
print(np.array(AB))
print("\nMatrix BA (B multiplied by A):")
print(np.array(BA))


Matrix A:
[[ 2 -1  3]
 [ 0  4  1]]

Matrix B:
[[ 1  2]
 [-2  0]
 [ 5 -3]]

Matrix AB (A multiplied by B):
[[19 -5]
 [-3 -3]]

Matrix BA (B multiplied by A):
[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
