

1. Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.

2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.

3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

4. Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.

5. Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)

6. Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.

In [ ]:
#1. Create a 6x6 NumPy array with random integers between 1 and 50. Display the array.
import numpy as np
import matplotlib.pyplot as plt
import time
import random

random_array = np.random.randint(1, 51, size=(6, 6))
 

print (random_array)

[[34 29 36  8 43 39]
 [ 4 16 40  8 22 50]
 [50 50 34 17 49 47]
 [20 21 17 17 30 35]
 [20 24  9 44 13 24]
 [34 22 40 39 11 40]]


In [ ]:
#2. Extract the following from the array you created in Question 1: The first two rows. The last three columns. All even numbers in the array.

row = random_array[:2, :] #First two rows
column = random_array[:, -3:] #last 3 columns
even_numbers = random_array[random_array % 2 == 0]
print("\nFirst two rows:\n", row)
print("\nLast three columns:\n", column)
print("\nAll even numbers:\n", even_numbers)





First two rows:
 [[34 29 36  8 43 39]
 [ 4 16 40  8 22 50]]

Last three columns:
 [[ 8 43 39]
 [ 8 22 50]
 [17 49 47]
 [17 30 35]
 [44 13 24]
 [39 11 40]]

All even numbers:
 [34 36  8  4 16 40  8 22 50 50 50 34 20 30 20 24 44 24 34 22 40 40]


In [ ]:
#3. Perform the following array transformations: Reshape the array into a 3D (3, 2, 6) array. Flatten the reshaped array back to 1D.

# Reshape to 3D: 2 layers × 2 rows × 3 columns  
reshaped_3d = random_array.reshape(3, 2, 6)
print("Reshaped to 3x2x6:\n", reshaped_3d)

# Flatten the reshaped array back to 1D
flattened =  reshaped_3d.flatten()  # Using flatten() to create a copy                
print("Flattened (copy):", flattened)

Reshaped to 3x2x6:
 [[[34 29 36  8 43 39]
  [ 4 16 40  8 22 50]]

 [[50 50 34 17 49 47]
  [20 21 17 17 30 35]]

 [[20 24  9 44 13 24]
  [34 22 40 39 11 40]]]
Flattened (copy): [34 29 36  8 43 39  4 16 40  8 22 50 50 50 34 17 49 47 20 21 17 17 30 35
 20 24  9 44 13 24 34 22 40 39 11 40]


In [18]:
#4. Generate a 4x4 identity matrix and replace the diagonal with numbers from 10 to 40, with a step of 10.
identity_matrix = np.eye(4)
print("Original identity matrix:\n", identity_matrix)   
np.fill_diagonal(identity_matrix, [10, 20, 30, 40])
print("Identity matrix with replaced diagonal:\n", identity_matrix)


Original identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Identity matrix with replaced diagonal:
 [[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


In [20]:
#Perform matrix multiplication between: A 3x4 matrix of random integers (1-10) A 4x3 matrix of random integers (1-10)
matrix_a = np.random.randint(1, 11, size=(3, 4))
print("Matrix A:\n", matrix_a)
matrix_b = np.random.randint(1, 11, size=(4, 3))
print("Matrix B:\n", matrix_b)
product = np.dot(matrix_a, matrix_b)    #or print("Product:", arr1matrix_a * arr2matrix_b)
print("The Product :\n", product)

Matrix A:
 [[ 1  9  1  6]
 [ 7  9  9 10]
 [ 3  1  1  5]]
Matrix B:
 [[ 7  4  6]
 [ 3  6 10]
 [ 3  9  5]
 [ 3  9  7]]
The Product :
 [[ 55 121 143]
 [133 253 247]
 [ 42  72  68]]


In [21]:
 #Create a function that takes a 2D NumPy array as input and returns a new array where: All even numbers are squared. All odd numbers are replaced by -1.
def transform_2d_array(arr):
    transformed = np.where(arr % 2 == 0, arr**2, -1)
    return transformed  
transformed_array = transform_2d_array(random_array)
print("\nTransformed array:\n", transformed_array)



Transformed array:
 [[1156   -1 1296   64   -1   -1]
 [  16  256 1600   64  484 2500]
 [2500 2500 1156   -1   -1   -1]
 [ 400   -1   -1   -1  900   -1]
 [ 400  576   -1 1936   -1  576]
 [1156  484 1600   -1   -1 1600]]
